### ISSUE TITLE
Output validation fails for preprocessing job in case of multiple serum channels

### ISSUE THREAD

**Issue by imagirom** [hci-unihd/batchlib#67] opened 2020-04-30 11:41 UTC
All outputs of the preprocessing job are wrongly classified as failed even if all the channels were processed correctly (downstream analysis is working fine).

Side note: this would be easier to debug if the error message included why some of the outputs failed.

**Comment by constantinpape** [comment] 2020-04-30 14:10
> All outputs of the preprocessing job are wrongly classified as failed even if all the channels were processed correctly (downstream analysis is working fine).

I can't reproduce this with the test and the one that uses [naming scheme 4](https://github.com/hci-unihd/batchlib/blob/master/data/test_data/naming_schemes/scheme4/channel_mapping.json) should in theory catch this.
Could you point me to an example where this fails?

> Side note: this would be easier to debug if the error message included why some of the outputs failed.

Yes, we should definitely add more debug logs for this ...

**Comment by imagirom** [comment] 2020-04-30 15:17
It also fails on `~/data/covid-data-vibor/20200405_test_images/`. It might have to do with explicitly specifying a`--folder`, which I always did.

**Comment by constantinpape** [comment] 2020-04-30 16:33
Ok, I will look into it later or tomorrow.

**Comment by constantinpape** [comment] 2020-05-01 12:43
I cannot reproduce this, @imagirom.
I tried
```
python cell_analysis_workflow.py --input_folder ~/data/covid-data-vibor/20200405_test_images/ --gpu 0 --n_cpus 12 --folder ~/data/sandbox/blub/20200405_test_images2
```
and several versions of this and they all work for me.

Could you try again on the latest commit?
Note that I removed the `ignore_failed_outputs=True` in https://github.com/hci-unihd/batchlib/pull/51/commits/5c4d645076f3c387b82e6fec5ed56f82889825d4.

**Comment by constantinpape** [comment] 2020-05-02 19:58
I think this is fixed now. Feel free to reopen if it comes up again.

**Closed by constantinpape** 2020-05-02 19:58 UTC
Labels: high priority

**Comment by imagirom** [comment] 2020-05-07 19:53
I have now finally figured out what was going on; It was indeed a local problem.
